export const ControlPacketType = {
	TRANSFER_OFFER: "TRANSFER_OFFER",
	TRANSFER_ACCEPT: "TRANSFER_ACCEPT",
	TRANSFER_REJECT: "TRANSFER_REJECT",
	TRANSFER_CANCEL: "TRANSFER_CANCEL",
	TRANSFER_OFFERED: "TRANSFER_OFFERED",
	TRANSFER_ACCEPTED: "TRANSFER_ACCEPTED",
	TRANSFER_REJECTED: "TRANSFER_REJECTED",
	TRANSFER_STATUS_CHANGED: "TRANSFER_STATUS_CHANGED",
	TRANSFER_PROGRESS_UPDATED: "TRANSFER_PROGRESS_UPDATED",
	TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
	TRANSFER_FAILED: "TRANSFER_FAILED",
	TRANSPORT_PLAN_CREATED: "TRANSPORT_PLAN_CREATED",
	TRANSPORT_PEERS_READY: "TRANSPORT_PEERS_READY",
	TRANSPORT_CHANGED: "TRANSPORT_CHANGED",
	TRANSPORT_FAILED: "TRANSPORT_FAILED",
	DEVICE_PRESENCE_CHANGED: "DEVICE_PRESENCE_CHANGED",
	DEVICE_WAKE_REQUESTED: "DEVICE_WAKE_REQUESTED",
	DEVICE_REVOKED: "DEVICE_REVOKED",
} as const;

export type ControlPacketType = (typeof ControlPacketType)[keyof typeof ControlPacketType];
