name: nekoshare

services:
    database:
        image: mysql:8.4.6
        restart: always
        env_file:
            - .env
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - nekoshare-net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

    migrate:
        build:
            context: ..
            dockerfile: apps/server/Dockerfile
            target: build
        container_name: nekoshare-migrate
        command: pnpm -C apps/server dz:p
        restart: "no"
        environment:
            - DB_HOST=database
            - DB_USER=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - DB_NAME=${MYSQL_DATABASE}
            - DB_PORT=3306
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        networks:
            - nekoshare-net
        depends_on:
            database:
                condition: service_healthy

    backend:
        build:
            context: ..
            dockerfile: apps/server/Dockerfile
        container_name: nekoshare-backend
        environment:
            - DB_HOST=database
            - DB_USER=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - DB_NAME=${MYSQL_DATABASE}
            - DB_PORT=3306
            - BETTER_AUTH_SECRET=some_random_secret_key # see https://www.better-auth.com/docs/installation#set-environment-variables
            - BETTER_AUTH_URL=http://localhost:7780
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        networks:
            - nekoshare-net
        ports:
            - "7780:7780"
            - "7781:7781"
        depends_on:
            database:
                condition: service_healthy
            migrate:
                condition: service_completed_successfully

volumes:
    mysql-data:

networks:
    nekoshare-net:
        driver: bridge
        name: nekoshare-net
        driver_opts:
            com.docker.network.bridge.enable_ip_masquerade: "true"
