/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteImport } from './routes/web'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIndexRouteImport } from './routes/share/$index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeItemsRouteImport } from './routes/home/items'
import { Route as HomeHistoryRouteImport } from './routes/home/history'
import { Route as HomeDevicesRouteImport } from './routes/home/devices'
import { Route as HomeContentRouteImport } from './routes/home/content'
import { Route as HomeBuddyShareRouteImport } from './routes/home/buddy-share'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPwdRouteImport } from './routes/auth/reset-pwd'
import { Route as AuthPasswordChangedRouteImport } from './routes/auth/password-changed'
import { Route as AuthNewPasswordRouteImport } from './routes/auth/new-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/share/$index',
  path: '/share/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeItemsRoute = HomeItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHistoryRoute = HomeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDevicesRoute = HomeDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContentRoute = HomeContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBuddyShareRoute = HomeBuddyShareRouteImport.update({
  id: '/buddy-share',
  path: '/buddy-share',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPwdRoute = AuthResetPwdRouteImport.update({
  id: '/reset-pwd',
  path: '/reset-pwd',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPasswordChangedRoute = AuthPasswordChangedRouteImport.update({
  id: '/password-changed',
  path: '/password-changed',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/desktop': typeof DesktopRoute
  '/web': typeof WebRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/password-changed': typeof AuthPasswordChangedRoute
  '/auth/reset-pwd': typeof AuthResetPwdRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/home/buddy-share': typeof HomeBuddyShareRoute
  '/home/content': typeof HomeContentRoute
  '/home/devices': typeof HomeDevicesRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/items': typeof HomeItemsRoute
  '/share/$index': typeof ShareIndexRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/desktop': typeof DesktopRoute
  '/web': typeof WebRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/password-changed': typeof AuthPasswordChangedRoute
  '/auth/reset-pwd': typeof AuthResetPwdRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/home/buddy-share': typeof HomeBuddyShareRoute
  '/home/content': typeof HomeContentRoute
  '/home/devices': typeof HomeDevicesRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/items': typeof HomeItemsRoute
  '/share/$index': typeof ShareIndexRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/desktop': typeof DesktopRoute
  '/web': typeof WebRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/password-changed': typeof AuthPasswordChangedRoute
  '/auth/reset-pwd': typeof AuthResetPwdRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/home/buddy-share': typeof HomeBuddyShareRoute
  '/home/content': typeof HomeContentRoute
  '/home/devices': typeof HomeDevicesRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/items': typeof HomeItemsRoute
  '/share/$index': typeof ShareIndexRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/desktop'
    | '/web'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/password-changed'
    | '/auth/reset-pwd'
    | '/auth/signup'
    | '/auth/verify'
    | '/home/buddy-share'
    | '/home/content'
    | '/home/devices'
    | '/home/history'
    | '/home/items'
    | '/share/$index'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/desktop'
    | '/web'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/password-changed'
    | '/auth/reset-pwd'
    | '/auth/signup'
    | '/auth/verify'
    | '/home/buddy-share'
    | '/home/content'
    | '/home/devices'
    | '/home/history'
    | '/home/items'
    | '/share/$index'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home'
    | '/desktop'
    | '/web'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/password-changed'
    | '/auth/reset-pwd'
    | '/auth/signup'
    | '/auth/verify'
    | '/home/buddy-share'
    | '/home/content'
    | '/home/devices'
    | '/home/history'
    | '/home/items'
    | '/share/$index'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  DesktopRoute: typeof DesktopRoute
  WebRoute: typeof WebRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$index': {
      id: '/share/$index'
      path: '/share/$index'
      fullPath: '/share/$index'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/items': {
      id: '/home/items'
      path: '/items'
      fullPath: '/home/items'
      preLoaderRoute: typeof HomeItemsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/history': {
      id: '/home/history'
      path: '/history'
      fullPath: '/home/history'
      preLoaderRoute: typeof HomeHistoryRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/devices': {
      id: '/home/devices'
      path: '/devices'
      fullPath: '/home/devices'
      preLoaderRoute: typeof HomeDevicesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/content': {
      id: '/home/content'
      path: '/content'
      fullPath: '/home/content'
      preLoaderRoute: typeof HomeContentRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/buddy-share': {
      id: '/home/buddy-share'
      path: '/buddy-share'
      fullPath: '/home/buddy-share'
      preLoaderRoute: typeof HomeBuddyShareRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-pwd': {
      id: '/auth/reset-pwd'
      path: '/reset-pwd'
      fullPath: '/auth/reset-pwd'
      preLoaderRoute: typeof AuthResetPwdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/password-changed': {
      id: '/auth/password-changed'
      path: '/password-changed'
      fullPath: '/auth/password-changed'
      preLoaderRoute: typeof AuthPasswordChangedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthPasswordChangedRoute: typeof AuthPasswordChangedRoute
  AuthResetPwdRoute: typeof AuthResetPwdRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthPasswordChangedRoute: AuthPasswordChangedRoute,
  AuthResetPwdRoute: AuthResetPwdRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeBuddyShareRoute: typeof HomeBuddyShareRoute
  HomeContentRoute: typeof HomeContentRoute
  HomeDevicesRoute: typeof HomeDevicesRoute
  HomeHistoryRoute: typeof HomeHistoryRoute
  HomeItemsRoute: typeof HomeItemsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeBuddyShareRoute: HomeBuddyShareRoute,
  HomeContentRoute: HomeContentRoute,
  HomeDevicesRoute: HomeDevicesRoute,
  HomeHistoryRoute: HomeHistoryRoute,
  HomeItemsRoute: HomeItemsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  DesktopRoute: DesktopRoute,
  WebRoute: WebRoute,
  ShareIndexRoute: ShareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
