/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPwdRouteImport } from './routes/(auth)/reset-pwd'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appHomeIndexRouteImport } from './routes/(app)/home/index'
import { Route as appShareNewRouteImport } from './routes/(app)/share/new'
import { Route as appHomeTransferDetailRouteImport } from './routes/(app)/home/transfer-detail'
import { Route as appHomeFriendsRouteImport } from './routes/(app)/home/friends'
import { Route as appHomeDevicesRouteImport } from './routes/(app)/home/devices'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPwdRoute = authResetPwdRouteImport.update({
  id: '/reset-pwd',
  path: '/reset-pwd',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appHomeIndexRoute = appHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => appRouteRoute,
} as any)
const appShareNewRoute = appShareNewRouteImport.update({
  id: '/share/new',
  path: '/share/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeTransferDetailRoute = appHomeTransferDetailRouteImport.update({
  id: '/home/transfer-detail',
  path: '/home/transfer-detail',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeFriendsRoute = appHomeFriendsRouteImport.update({
  id: '/home/friends',
  path: '/home/friends',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeDevicesRoute = appHomeDevicesRouteImport.update({
  id: '/home/devices',
  path: '/home/devices',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/reset-pwd': typeof authResetPwdRoute
  '/signup': typeof authSignupRoute
  '/home/devices': typeof appHomeDevicesRoute
  '/home/friends': typeof appHomeFriendsRoute
  '/home/transfer-detail': typeof appHomeTransferDetailRoute
  '/share/new': typeof appShareNewRoute
  '/home': typeof appHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/reset-pwd': typeof authResetPwdRoute
  '/signup': typeof authSignupRoute
  '/home/devices': typeof appHomeDevicesRoute
  '/home/friends': typeof appHomeFriendsRoute
  '/home/transfer-detail': typeof appHomeTransferDetailRoute
  '/share/new': typeof appShareNewRoute
  '/home': typeof appHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-pwd': typeof authResetPwdRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/home/devices': typeof appHomeDevicesRoute
  '/(app)/home/friends': typeof appHomeFriendsRoute
  '/(app)/home/transfer-detail': typeof appHomeTransferDetailRoute
  '/(app)/share/new': typeof appShareNewRoute
  '/(app)/home/': typeof appHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-pwd'
    | '/signup'
    | '/home/devices'
    | '/home/friends'
    | '/home/transfer-detail'
    | '/share/new'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-pwd'
    | '/signup'
    | '/home/devices'
    | '/home/friends'
    | '/home/transfer-detail'
    | '/share/new'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(auth)/login'
    | '/(auth)/reset-pwd'
    | '/(auth)/signup'
    | '/(app)/home/devices'
    | '/(app)/home/friends'
    | '/(app)/home/transfer-detail'
    | '/(app)/share/new'
    | '/(app)/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-pwd': {
      id: '/(auth)/reset-pwd'
      path: '/reset-pwd'
      fullPath: '/reset-pwd'
      preLoaderRoute: typeof authResetPwdRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/home/': {
      id: '/(app)/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/share/new': {
      id: '/(app)/share/new'
      path: '/share/new'
      fullPath: '/share/new'
      preLoaderRoute: typeof appShareNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/home/transfer-detail': {
      id: '/(app)/home/transfer-detail'
      path: '/home/transfer-detail'
      fullPath: '/home/transfer-detail'
      preLoaderRoute: typeof appHomeTransferDetailRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/home/friends': {
      id: '/(app)/home/friends'
      path: '/home/friends'
      fullPath: '/home/friends'
      preLoaderRoute: typeof appHomeFriendsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/home/devices': {
      id: '/(app)/home/devices'
      path: '/home/devices'
      fullPath: '/home/devices'
      preLoaderRoute: typeof appHomeDevicesRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appHomeDevicesRoute: typeof appHomeDevicesRoute
  appHomeFriendsRoute: typeof appHomeFriendsRoute
  appHomeTransferDetailRoute: typeof appHomeTransferDetailRoute
  appShareNewRoute: typeof appShareNewRoute
  appHomeIndexRoute: typeof appHomeIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appHomeDevicesRoute: appHomeDevicesRoute,
  appHomeFriendsRoute: appHomeFriendsRoute,
  appHomeTransferDetailRoute: appHomeTransferDetailRoute,
  appShareNewRoute: appShareNewRoute,
  appHomeIndexRoute: appHomeIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authResetPwdRoute: typeof authResetPwdRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authResetPwdRoute: authResetPwdRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
