export const TransferErrorCode = {
	TRANSFER_NOT_FOUND: "TRANSFER_NOT_FOUND",
	TRANSFER_FORBIDDEN: "TRANSFER_FORBIDDEN",
	TRANSFER_INVALID_STATE: "TRANSFER_INVALID_STATE",
	TRANSFER_EXPIRED: "TRANSFER_EXPIRED",
	DEVICE_OFFLINE: "DEVICE_OFFLINE",
	DEVICE_REVOKED: "DEVICE_REVOKED",
	TRANSPORT_TIMEOUT: "TRANSPORT_TIMEOUT",
	TRANSPORT_NOT_READY: "TRANSPORT_NOT_READY",
	TRANSPORT_DISCONNECTED: "TRANSPORT_DISCONNECTED",
	RELAY_TICKET_EXPIRED: "RELAY_TICKET_EXPIRED",
	RELAY_TICKET_INVALID: "RELAY_TICKET_INVALID",
	RELAY_PEER_DISCONNECTED: "RELAY_PEER_DISCONNECTED",
	SOURCE_FILE_MISSING: "SOURCE_FILE_MISSING",
	RECEIVER_DISK_FULL: "RECEIVER_DISK_FULL",
	PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
	PROTOCOL_VIOLATION: "PROTOCOL_VIOLATION",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type TransferErrorCode =
	(typeof TransferErrorCode)[keyof typeof TransferErrorCode];

export function isRetryableTransferError(code: TransferErrorCode): boolean {
	return (
		code === TransferErrorCode.DEVICE_OFFLINE ||
		code === TransferErrorCode.TRANSPORT_TIMEOUT ||
		code === TransferErrorCode.TRANSPORT_NOT_READY ||
		code === TransferErrorCode.TRANSPORT_DISCONNECTED ||
		code === TransferErrorCode.RELAY_PEER_DISCONNECTED ||
		code === TransferErrorCode.INTERNAL_ERROR
	);
}
