export const TransferErrorCode = {
	TRANSFER_NOT_FOUND: "TRANSFER_NOT_FOUND",
	TRANSFER_INVALID_STATE: "TRANSFER_INVALID_STATE",
	TRANSFER_UNAUTHORIZED_DEVICE: "TRANSFER_UNAUTHORIZED_DEVICE",
	TRANSFER_TARGET_OFFLINE: "TRANSFER_TARGET_OFFLINE",
	TRANSFER_EXPIRED: "TRANSFER_EXPIRED",
	TRANSPORT_FAILED: "TRANSPORT_FAILED",
	RELAY_TICKET_EXPIRED: "RELAY_TICKET_EXPIRED",
	RELAY_LIMIT_EXCEEDED: "RELAY_LIMIT_EXCEEDED",
	PAYLOAD_INVALID: "PAYLOAD_INVALID",
	CHECKSUM_MISMATCH: "CHECKSUM_MISMATCH",
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	PERMISSION_DENIED: "PERMISSION_DENIED",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type TransferErrorCode = (typeof TransferErrorCode)[keyof typeof TransferErrorCode];

export interface TransferErrorPayload {
	transferId: string;
	code: TransferErrorCode;
	message: string;
	retryable: boolean;
}
